[package]
name = "boa"
version = "0.1.0"
authors = ["fox"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gc = "0.3.3"

[dependencies.Boa]
git = "https://github.com/jasonwilliams/boa.git"
revision = "1e08149"
