language: rust
cache: cargo
os:
  - linux
before_install:
  - sudo apt-get update
  - cargo install just --force
  - sudo apt-get install liblz4-dev
  - sudo apt-get install musl-dev
  - sudo apt-get install musl-tools
  - rustup target add x86_64-unknown-linux-musl
  - rustup target add aarch64-unknown-linux-musl
rust:
  - nightly
script:
  - just build-x86_64
#  - just build-aarch64